/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import Conexion.Conectar;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DiamondStalker
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    DefaultTableModel Model;
    String titulos[] = {"Nombre", "Cantidad", "Precio", "Olor", "Fecha_vencimiento"};

    /**
     * Creates new form Pantalla
     */
    public MainJframe() {
        initComponents();
        ImageIcon icon = new ImageIcon("src\\Images/iconos-01.png");
        this.setIconImage(icon.getImage());
        Model = new DefaultTableModel() {
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return String.class;
                    case 1:
                        return String.class;
                    case 2:
                        return String.class;
                    case 3:
                        return String.class;
                    case 4:
                        return String.class;

                    default:
                        return String.class;
                }
            }
        };

        for (String x : titulos) {
            Model.addColumn(x);
        }
        this.TablaAseo.setModel(Model);

        Object[][] Datos = cargar_datos();
        for (Object[] Dato : Datos) {
            Object[] add = new Object[5];
            add[0] = Dato[0];
            add[1] = Dato[1];
            add[2] = Dato[2];
            add[3] = Dato[3];
            add[4] = Dato[4];
            Model.addRow(add);
        }

    }

    public static Conectar cn = new Conectar();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtolor = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cantidad = new javax.swing.JSpinner();
        Crear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAseo = new javax.swing.JTable();
        DATE = new com.toedter.calendar.JDateChooser();
        TextoInfo = new javax.swing.JLabel();
        Cargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Productos Aseo");
        setIconImage(getIconImage());

        jLabel1.setText("Productos Aseo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Cantidad");

        jLabel4.setText("Precio");

        jLabel5.setText("Olor");

        jLabel6.setText("Fecha vencimiento");

        cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantidad.setToolTipText("");

        Crear.setText("Agragar");
        Crear.setAutoscrolls(true);
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        TablaAseo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Precio", "Olor", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaAseo.setToolTipText("");
        jScrollPane1.setViewportView(TablaAseo);

        DATE.setToolTipText("");
        DATE.setName("Date"); // NOI18N

        TextoInfo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        TextoInfo.setForeground(new java.awt.Color(255, 255, 51));

        Cargar.setText("Cargar");
        Cargar.setAutoscrolls(true);
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                            .addComponent(cantidad))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtolor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(DATE, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(299, 299, 299))))
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(432, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TextoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(338, Short.MAX_VALUE)
                    .addComponent(Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(160, 160, 160)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        String Nombre = txtnombre.getText();
        int precio = 0;
        int catidad = 0;
        boolean Correcto = false;
        try {
            catidad = (int) cantidad.getValue();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Inserta una un valor para cantidad correcta");
            Correcto = false;
        }
        try {
            precio = Integer.parseInt(txtprecio.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingresa un valor de precio sin simbolos espacioales");
            Correcto = false;
        }

        String Olor = txtolor.getText();

        Date date = DATE.getDate();
        String dateStr = "";
        try {
            DateFormat dateFormat = new SimpleDateFormat("d/M/yy");
            dateStr = dateFormat.format(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Inserta una fecha de vencimineto valido");
            Correcto = false;
        }

        Correcto = Nombre != "" ? true : false;
        Correcto = Olor != "" ? true : false;
        if (Correcto) {
            if (cn.nuevoproducto(Nombre, catidad, precio, Olor, dateStr)) {
                Object Datos[] = new Object[5];
                Datos[0] = Nombre;
                Datos[1] = catidad;
                Datos[2] = precio;
                Datos[3] = Olor;
                Datos[4] = dateStr;
                Model.addRow(Datos);
                Limpiar();
                TextoInfo.setForeground(Color.GREEN);
                ImageIcon icon = new ImageIcon("src\\Images/correcto.png");
                TextoInfo.setIcon(icon);
                TextoInfo.setText("Se inserto el usuario de forma correcta");
            } else {
                TextoInfo.setForeground(Color.BLUE);
                ImageIcon icon = new ImageIcon("src\\Images/info.png");
                TextoInfo.setIcon(icon);
                TextoInfo.setText("Completa todos los campos para poder continuar");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El usuario ya se encuentra insertado");
            TextoInfo.setForeground(Color.RED);
            TextoInfo.setText("EL usuario ya existe");
        }

    }//GEN-LAST:event_CrearActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
        int datos = Model.getRowCount();
        System.out.println("Hay " + datos + " datos en la tabla");
        for (int i = 0; i < datos; i++) {
            Model.removeRow(0);
        }

        Object[][] Datos = cargar_datos();
        for (Object[] Dato : Datos) {
            Object[] add = new Object[5];
            add[0] = Dato[0];
            add[1] = Dato[1];
            add[2] = Dato[2];
            add[3] = Dato[3];
            add[4] = Dato[4];
            
            Model.addRow(add);
        }
    }//GEN-LAST:event_CargarActionPerformed

    public void cargartabla() {
         int datos = Model.getRowCount();
        System.out.println("Hay " + datos + " datos en la tabla");
        for (int i = 0; i < datos; i++) {
            Model.removeRow(0);
        }
        Object[][] Datos = cargar_datos();
        for (Object[] Dato : Datos) {
            Object[] add = new Object[5];
            add[0] = Dato[0];
            add[1] = Dato[1];
            add[2] = Dato[2];
            add[3] = Dato[3];
            add[4] = Dato[4];
            Model.addRow(add);
        }
    }

    public Object[][] cargar_datos() {
        Object[][] Usuarios = cn.Usuarios();

        for (int i = 0; i < Usuarios.length; i++) {
            System.out.println("Nombre --> " + Usuarios[i][0]
                    + "**Cantidad --> " + Usuarios[i][1]
                    + "**Precio --> " + Usuarios[i][2]
                    + "**Olor --> " + Usuarios[i][3]
                    + "**fecha_vencimiento --> " + Usuarios[i][4]);
        }
        return Usuarios;
    }

    public void Limpiar() {
        txtnombre.setText("");
        cantidad.setValue(0);
        txtprecio.setText("");
        SimpleDateFormat formatter = new SimpleDateFormat("d/M/yy");
        Date date = new Date(System.currentTimeMillis());
        DATE.setDate(date);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cargar;
    private javax.swing.JButton Crear;
    private com.toedter.calendar.JDateChooser DATE;
    private javax.swing.JTable TablaAseo;
    private javax.swing.JLabel TextoInfo;
    private javax.swing.JSpinner cantidad;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtolor;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
